### ISSUE TITLE
NoClassDefFoundError - NavigationView

### ISSUE THREAD

**Issue by LeandroHenriqueSS** [Hand-Talk/android-library#29]
Estou recebendo um NoClassDefFoundError quando tento pegar uma instância do SDK.

Segue a linha da falha (localizada no onResumo):
HandTalkSDK handTalk = HandTalkSDK.getInstance(this);

Segue a saída do LogCat:

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/design/widget/NavigationView;
                                                                                                    at br.com.handtalk.androidlib.HandTalkSDK.findAllViews(HandTalkSDK.java:224)
                                                                                                    at br.com.handtalk.androidlib.HandTalkSDK.turnAllElementsSelectable(HandTalkSDK.java:214)
                                                                                                    at br.com.handtalk.androidlib.HandTalkSDK.<init>(HandTalkSDK.java:100)
                                                                                                    at br.com.handtalk.androidlib.HandTalkSDK.getInstance(HandTalkSDK.java:84)
                                                                                                    at funappsstudios.com.testlibrasparayoutubeenetflix.MainActivity.onResume(MainActivity.java:21)

**Comment by carlosuebbi** [comment]
Oi Leandro,

Desde já agradeço você estar testando a nossa Lib.
Esse erro é porque se faz necessário você importar nas dependências a
biblioteca de DESIGN do android.

compile 'com.android.support:design:25.1.0'

Adiciona e roda novamente para ver funcionando.
Me confirma por favor se deu certo, ok?

Obrigado


Atenciosamente,




  *Carlos Wanderlan*
  CTO - Chief Technical Officer
  carlos@handtalk.com.br
  82 3022-8060 | 82 99351-7772
  Skype ID: carloswanderlan | Site <http://www.handtalk.me/> | Facebook
<https://www.facebook.com/handtalkBR>



*Informações Importantes:*

De acordo o *CENSO 2010 do IBGE*, o Brasil possui quase *10 milhões de
pessoas* com algum tipo de problema auditivo, desse número, aproximadamente *3
milhões são surdos totais, severos*. Aproximadamente 70% desses surdos não
compreende corretamente o português e dependem exclusivamente da Libras
para se comunicar.

On Sun, May 28, 2017 at 9:45 PM, LeandroHenriqueSS <notifications@github.com

**Comment by LeandroHenriqueSS** [comment]
Consegui sim, Carlos. Valeu!

**Comment by carlosuebbi** [comment]
Excelente Leandro,

Me dá mais algum feedback, em que está usando para testes?
O que achou da ferramenta?
O que você acha que poderíamos melhorar nesse BETA?

Obrigado mesmo!


Atenciosamente,




  *Carlos Wanderlan*
  CTO - Chief Technical Officer
  carlos@handtalk.com.br
  82 3022-8060 | 82 99351-7772
  Skype ID: carloswanderlan | Site <http://www.handtalk.me/> | Facebook
<https://www.facebook.com/handtalkBR>



*Informações Importantes:*

De acordo o *CENSO 2010 do IBGE*, o Brasil possui quase *10 milhões de
pessoas* com algum tipo de problema auditivo, desse número, aproximadamente *3
milhões são surdos totais, severos*. Aproximadamente 70% desses surdos não
compreende corretamente o português e dependem exclusivamente da Libras
para se comunicar.

**Comment by LeandroHenriqueSS** [comment]
1) Estou fazendo uma aplicação de tradução em tempo real

2) A ferramenta tá ótima. O código tá bem escrito

3) Sinto falta de mais controles para personalizar minha aplicação. A classe UnityPlayer está ofuscada e estou com dificuldades para fazer alterações que possa refletir diretamente no player nativo Unity, como por exemplo definir a duração e eliminar atrasos pré e pós execução da animação.
