### ISSUE TITLE
Atraso na chamada do método 'OnAnimationEnd()' após a finalização da animação

### ISSUE THREAD

**Issue by LeandroHenriqueSS** [Hand-Talk/android-library#30]
Olá,

Estou utilizando o Hand Talk para fazer uma aplicação de tradução em tempo real.

Em meus testes, utilizo a própria classe HugoActivity e envio uma nova mensagem para ser traduzida sempre que a anterior é finalizada através do método 'playHugo(textToTranslate)'. No entanto, percebi que o método 'OnAnimationEnd()' só é chamado cerca de 1 segundo após o Hugo já ter finalizado seus movimentos, o que acaba inviabilizando minha aplicação.

Há alguma forma de eliminar esse atraso?

Também estou sentindo falta de alguns métodos como:
- Alterar velocidade de animação
- Remover o texto que fica em cima do Hugo

**Comment by carlosuebbi** [comment]
Oi Leandro, tudo bem? Então, podemos estudar essas possibilidades para uma próxima versão da biblioteca, nesse momento não temos esses outros métodos. Antes de lançarmos oficialmente isto estará implementado.
Assim que disponibilizarmos essas modificações eu já te aviso. Pode ser?

**Comment by LeandroHenriqueSS** [comment]
Obrigado por responder, Carlos.

Tudo ótimo. Vou continuar meus testes aqui e tentarei contribuir com o que eu puder.

**Comment by carlosuebbi** [comment]
Maravilha Leandro, obrigado mesmo! ;)


Atenciosamente,




  *Carlos Wanderlan*
  CTO - Chief Technical Officer
  carlos@handtalk.com.br
  82 3022-8060 | 82 99351-7772
  Skype ID: carloswanderlan | Site <http://www.handtalk.me/> | Facebook
<https://www.facebook.com/handtalkBR>



*Informações Importantes:*

De acordo o *CENSO 2010 do IBGE*, o Brasil possui quase *10 milhões de
pessoas* com algum tipo de problema auditivo, desse número, aproximadamente *3
milhões são surdos totais, severos*. Aproximadamente 70% desses surdos não
compreende corretamente o português e dependem exclusivamente da Libras
para se comunicar.

On Mon, Jun 12, 2017 at 3:09 PM, LeandroHenriqueSS <notifications@github.com
